import type { Regimen } from "@/types/game";
import { calcularParticipacion } from "./regimenes";

export type DecisionRapida = { titulo: string; situacion: string; opciones: string[]; correcta: number; explicacion: string; articulo: string };
/** Mismo caso, tres reglas. Sin efectos ni dependencia del store de campaña. */
export function decisionesRapidas(regimen: Regimen): DecisionRapida[] {
  const sc = regimen === "sociedad_conyugal";
  const pg = regimen === "participacion_gananciales";
  const credito = calcularParticipacion(40, 70, 10, 60).credito;
  return [
    { titulo: "01 · El sueldo y el sello", situacion: "Tomás y Elena están casados. Tomás recibe $1.500.000 por su trabajo durante el matrimonio. El funcionario pregunta a qué patrimonio pertenece. La impresora ya ha solicitado vacaciones.", opciones: ["Haber absoluto de la sociedad conyugal", "Patrimonio individual de Tomás", "La mitad es automáticamente de Elena"], correcta: sc ? 0 : 1, explicacion: sc ? "La remuneración devengada durante la sociedad conyugal integra el haber absoluto. No basta mirar a nombre de quién se pagó." : `Tomás mantiene su patrimonio individual. ${pg ? "Al finalizar podrá existir un crédito de participación, no una comunidad inmediata sobre el sueldo." : "El matrimonio no crea una masa social."}`, articulo: sc ? "Art. 1725 N°1 CC" : pg ? "Art. 1792-2 CC" : "Art. 159 CC" },
    { titulo: "02 · La casa no es un comodín", situacion: "La vivienda principal pertenece a Elena y ha sido declarada bien familiar. ¿La declaración transforma a Tomás en dueño de la mitad?", opciones: ["Sí, la declaración divide el dominio", "No; protege la vivienda sin cambiar su titularidad", "Sólo si lo autoriza la impresora"], correcta: 1, explicacion: "La afectación como bien familiar protege la vivienda y limita ciertos actos; no transfiere el dominio. Es una institución aplicable con independencia del régimen matrimonial.", articulo: "Arts. 141–142 CC" },
    { titulo: "03 · Cerrar sin invocar fantasmas", situacion: sc ? "Caso independiente de cierre: luego de inventario, deudas y recompensas, hay $20 millones de gananciales. No hay renuncia ni otra excepción en este supuesto. ¿Cómo se divide el remanente?" : pg ? "Balances netos ajustados a la misma fecha: Tomás pasa de $40 a $70 millones; Elena, de $10 a $60 millones. Sin ajustes pendientes. ¿Qué resulta?" : "Al terminar el régimen sólo constan bienes individuales. No se acreditan copropiedad ni créditos pendientes. ¿Qué corresponde?", opciones: sc ? ["$10 millones para cada uno", "Todo para quien figura en más escrituras", "Repartir también todos los bienes propios"] : pg ? ["Partir cada bien en dos", `Crédito de $${credito} millones para Tomás`, "Elena pierde todo su patrimonio"] : ["Cada titular conserva sus bienes", "Repartir todo por mitades", "Abrir un haber relativo"], correcta: sc ? 0 : pg ? 1 : 0, explicacion: sc ? "Se divide el remanente neto por mitades en este supuesto. No se adjudican automáticamente bienes propios ni se reparte por cantidad de objetos." : pg ? "Ganancias: Tomás 30, Elena 50. La mitad de la diferencia es 10. Nace un crédito a favor de Tomás, no dominio sobre la mitad de los bienes de Elena." : "No hay sociedad conyugal que liquidar. Si existieran copropiedad o créditos acreditados, deben revisarse por sus propias reglas.", articulo: sc ? "Art. 1774 CC" : pg ? "Arts. 1792-6 y 1792-19 CC" : "Art. 159 CC" },
  ];
}
